from("telegram:bots?authorizationToken={{my.telegram-token}}")
    .choice()
        .when()
            .simple('${in.body} != null')
            .to("direct:response1")

// from("direct:response1")
//     .log('Incoming message from Telegram is ${in.body}')
//     .setBody()
//         .simple('You  said \"${in.body}\"?')
//         .to("telegram:bots?authorizationToken=")

from("direct:response1")
    .log('Incoming message from Telegram is:  \"${in.body}\"')
        .choice()
        .when(simple('${bodyAs(java.lang.String)} contains "#funny"'))
        .setBody()
            .simple('Did anyone said something #funny? ;)')
            .to("telegram:bots?authorizationToken={{my.telegram-token}}}}")
