apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: telegram-sink-binding
spec:
  source:
    ref:
      kind: InMemoryChannel
      apiVersion: messaging.knative.dev/v1
      name: messages

  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: telegram-simple-sink
    properties:
      authorizationToken: "5192208346:AAGTcJjERQYOpP4f0TgQwVPGZUJ_iQBT3io"
      chatId: "1023325072"

      